# Generated by Django 5.1.1 on 2024-09-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('ano', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('disponivel', 'Disponível')], default='disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.contato')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.item')),
            ],
        ),
    ]
