# Generated by Django 5.1.1 on 2024-09-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
    ]
